- name: Install Jenkins
  hosts: server1
  become: yes
  roles:
    - role-jenkins

- name: Install Gitlab
  hosts: server2
  become: yes
  roles:
    - role-gitlab

- name: Install Nexus
  hosts: server3
  become: yes
  roles:
    - role-nexus

- name: Install Sonar
  hosts: server4
  become: yes
  roles:
    - role-sonarqube

- name: Install Jenkins Slave
  hosts: server5
  become: true
  roles:
    - role-slave-jenkins



