
  
    # - name: Pull default Docker image prometheus+grafana
    #   become: yes
    #   docker_image:
    #     name: sonarqube:community
    #     source: pull

    - name: install prometheus+grafana
      become: yes
      shell: |
        

        kubectl create namespace prometheus
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update


        helm install prometheus prometheus-community/prometheus-operator --namespace prometheus
        kubectl patch svc prometheus-server -n prometheus-grafana -p '{"spec": {"type": "LoadBalancer"}}'

        helm install grafana grafana/grafana --namespace prometheus-grafana
        kubectl patch svc grafana -n prometheus-grafana -p '{"spec": {"type": "LoadBalancer"}}'



    - name: sleep wait
      command: /bin/sleep 40

    - name: cat pass grafana
      become: yes
      command: bash -c "kubectl get secret --namespace prometheus-grafana grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo"
      register: pass_grafana

 
    - debug:
        var: pass_grafana.stdout_lines
        

