   
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull image gitlab-ce
      docker_image:
        name: gitlab/gitlab-ce:latest
        source: pull
    
    - name: chmod /var/run/docker.sock
      become: yes
      shell: |
        sudo chmod 777 /var/run/docker.sock

    - name: command install gitlab
      command: bash -c "docker run --restart unless-stopped --detach --publish 8011:443 --publish 8012:80 --publish 8013:22 --name gitlab-sv --volume `pwd`/config-gl/config:/etc/gitlab --volume `pwd`/logs-gl/logs:/var/log/gitlab --volume `pwd`/data-gl/data:/var/opt/gitlab gitlab/gitlab-ce:latest"
    
    - name: sleep wait
      command: /bin/sleep 40

    - name: cat pass gitlab
      command: bash -c "docker exec -it gitlab-sv grep 'Password:' /etc/gitlab/initial_root_password"
      register: pass_git
 
    - debug:
        var: pass_git.stdout_lines

